exception: ensure that we use the correct 'wrap' reference in captureStackTrace()
There's the possibility of some asshole overwriting
`require('NodObjC/lib/exception').wrap`, so we should guard against that.